// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Models;

#nullable disable

namespace ProductsAPI.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20241126083428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            IsActive = true,
                            Price = 800m,
                            ProductName = "Iphone 14"
                        },
                        new
                        {
                            ProductID = 2,
                            IsActive = true,
                            Price = 1000m,
                            ProductName = "Iphone 15"
                        },
                        new
                        {
                            ProductID = 3,
                            IsActive = true,
                            Price = 1499m,
                            ProductName = "Iphone 16"
                        },
                        new
                        {
                            ProductID = 4,
                            IsActive = false,
                            Price = 1899m,
                            ProductName = "Iphone 16 Pro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
